### ISSUE TITLE
ERRORE visualizzazione dettagli anagrafica

### ISSUE THREAD

**Issue by hacosmin** [physio/anigest#102]
se vai nell'elenco delle anagrafiche e fai click sul nome di un cliente dovrebbe venire fuori il dettaglio dell''anagraffica. 

adesso viene fuori un errore in rosso lungo 1 KM

**Comment by physio** [comment]
e' strano perche' ho visto che invece i contatti che hanno messo gli indiani funziona tutto. l'errore e' sui media. hai caricato qualche cosa per caso?

**Comment by hacosmin** [comment]
Sul profilo mio ho caricato un avatar

Il 9 mag 2017 10:46 AM, "physio" <notifications@github.com> ha scritto:

**Comment by physio** [comment]
no no intendevo se hai caricato dei media sui clienti

**Comment by hacosmin** [comment]
Mi sembra di no

Il 9 mag 2017 10:54 AM, "physio" <notifications@github.com> ha scritto:
