### ISSUE TITLE
geolocal - gestione fornitori

### ISSUE THREAD

**Issue by hacosmin** [physio/anigest#73]
se ho il fornitore Abilene selezionato e faccio NUOVO FORNITORE si apre una finestra con i 2 campi vuoti, compilo i campi con WIFI4ALL ma invece di aggiungere il nuovo mi va a modificare(solo nome e descrizione) di quello selezionato. Mantiene cmq tutti i ripetitori gia salvati

**Comment by physio** [comment]
non credo di aver capito. A me questo problema non si e' presentato. sono riuscito ad inserire al primo tentativo WIFI4ALL. cosa non mi e' chiaro?
