### ISSUE TITLE
GRAFICA inserimento/modifica nuova anagrafica

### ISSUE THREAD

**Issue by hacosmin** [physio/anigest#90]
l'inserimento di una nuova anagrafica mi sembra un po macchinosa(troppe finestre). Si può prendere come spunto quella dei contatti di gmail ?   Unica schermata dove inserisci tutti i dati (nome, cognome, n indirizzi, n telefoni, )
![screenhunter 01](https://cloud.githubusercontent.com/assets/8323698/25270417/f192a6ae-2680-11e7-8b91-e071d9395855.jpg)

**Comment by physio** [comment]
verrà richiesta valutazione economica dello sviluppo.
