### ISSUE TITLE
Modifica colori dei puntini sulla mappa

### ISSUE THREAD

**Issue by hacosmin** [physio/anigest#91]
3P System - ROSSO
Wifi4All - GIALLO
Tiscali - VIOLA
Abilene Net Solutions - AZZURO

**Comment by physio** [comment]
i colori dei marker vengono posti in automatico dal sistema. se il provider cambia il suo marker allora agli installatori comparirà la relativa icona. se tu hai le icone passamele che le sostituiamo noi a mano.
