### ISSUE TITLE
ERRORE Descrizione tipo intervento da mappa

### ISSUE THREAD

**Issue by hacosmin** [physio/anigest#92]
Se faccio click sul puntino di GHIRARDO ENRICO si apre la nuvoletta con un po di dati.

il TIPO DI INTERVENTO viene riportato sbagliato.    E' un'installazione ma nella nuvoletta viene riportato SMONTAGGIO

**Comment by physio** [comment]
non si capisce na sega.

**Comment by hacosmin** [comment]
1. vai sulla mappa
2. cerchi GHIRARDO ENRICO e clicki sul puntino
3. si apre la nuvoletta con i dettagli dell'intervento, c'è scritto: Smontaggio in carico a HARALAMBIE Cosmin, 
4. se tu vai nella sezione interventi vedrai k l'intervento di GHIRARDO e un'installazione non uno smontaggio

capio desso?

**Comment by physio** [comment]
errore verificato

**Comment by physio** [comment]
corretto.
