### ISSUE TITLE
ERRORE - END DATE si imposta in automatico

### ISSUE THREAD

**Issue by hacosmin** [physio/anigest#95]
esempio da guardare: INTERVENTO DI GHIRARDO ENRICO
1. chiamo il cliente e prendo appuntamento 
2.  vado nel intervento e faccio ADD DATE
3. imposto il campo START DATE per il 28.04.2017 ore 14.00

perché il campo END TIME si imposta in automatico con la data del 28.04.2017 ore 01.00 ????

devo essere io a impostare END TIME a mano quando ho finito

**Comment by physio** [comment]
un endtime ci deve essere per forza, altrimenti non e' possibile creare l'appuntamento sul calendario. se ci fai caso anche google calendar imposta gli eventi alla durata standard di 30 minuti. se vuoi possiamo impostare 2 ore di intervento standard (in anigest 1 erano 3 non modificabili), e poi si modificano come si vuole.

**Comment by hacosmin** [comment]
Va benissimo 2h allora

Il 27 apr 2017 9:59 PM, "physio" <notifications@github.com> ha scritto:

**Comment by physio** [comment]
corretto.
